// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  learningSidebar: [
    'intro',
    {
      type: 'category',
      label: 'SQL',
      collapsed: true,
      items: [
        'SQL/intro',
        'SQL/chapter/chapter-01',
        'SQL/chapter/chapter-02',
        'SQL/chapter/chapter-03',
        'SQL/chapter/chapter-04',
        'SQL/chapter/chapter-05',
        'SQL/chapter/chapter-06',
        'SQL/chapter/chapter-07',
        'SQL/chapter/chapter-08',
        'SQL/chapter/chapter-09',
        'SQL/chapter/chapter-10',
        'SQL/chapter/chapter-11',
        'SQL/chapter/chapter-12',
        'SQL/chapter/chapter-13',
        'SQL/chapter/chapter-14',
        'SQL/chapter/chapter-15',


      ],
    },
    {
      type: 'category',
      label: 'Linq',
      collapsed: true,
      items: [
        'Linq/intro',
        'Linq/chapter/chapter-01',
        'Linq/chapter/chapter-02',
        'Linq/chapter/chapter-03',
        'Linq/chapter/chapter-04',
        'Linq/chapter/chapter-05',
        'Linq/chapter/chapter-06',
        'Linq/chapter/chapter-07',
        'Linq/chapter/chapter-08',
        'Linq/chapter/chapter-09',
        'Linq/chapter/chapter-10',
        'Linq/chapter/chapter-11',
        'Linq/chapter/chapter-12',
        'Linq/chapter/chapter-13',
        'Linq/chapter/chapter-14',
      ],
    },
    // ... other categories
  ],

};

export default sidebars;
